### ISSUE TITLE
Cannot compile hwsl2-0.1.1.4 with GHC 7.8.4 on Linux/x86_64

### ISSUE THREAD

**Issue by peti** [srijs/coholos#1]
A complete build log that shows the errors I'm seeing is available at http://hydra.cryp.to/build/560043/nixlog/2/raw.

**Comment by srijs** [comment]
This actually looks like the same bug that is causing https://github.com/NixOS/nixpkgs/issues/5900, tracked in https://github.com/haskell/cabal/issues/2039 and reported to upstream (GHC) here: https://ghc.haskell.org/trac/ghc/ticket/9625

```
Linking dist/build/testStub/testStub ...
ghc: panic! (the 'impossible' happened)
  (GHC version 7.8.4 for x86_64-unknown-linux):
    Don't understand library name test
```

Since you participated in the first issue, are you aware of any workarounds yet?

**Comment by peti** [comment]
Unfortunately, I am not aware of any workarounds.

**Comment by srijs** [comment]
Can you provide the exact command that was used to build the package?

**Comment by peti** [comment]
```
./Setup --verbose --enable-split-objs --disable-library-profiling --enable-shared --enable-library-vanilla --enable-executable-dynamic --enable-tests
./Setup build
./Setup test
```

**Comment by srijs** [comment]
Okay, so I played around a bit, and unfortunately the only thing I can recommend is don't use `--enable-executable-dynamic` and `--enable-tests` together. If you really want to install the library with `--enable-executable-dynamic`, I suggest building, reconfiguring (without `--enable-executable-dynamic`), testing, cleaning, reconfiguring (with `--enable-executable-dynamic`) and installing.

I realise this is not a great solution, but since this is an upstream bug, my hands are pretty much tied, sorry :(
